language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      os: linux
   -  name: "Python 3.7 on ARM machine with Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
      arch: arm64
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

jobs:
  allow_failures:
    - os: windows

cache: pip

addons:
  apt:
    packages:
        gcc
        gfortran
        libc-dev
        python-dev

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - python3 setup.py install || python setup.py install

script:
  - python3 magpy/test/test_di.py || python magpy/test/test_di.py
  - python3 magpy/test/test_read_write.py|| python magpy/test/test_read_write.py

