language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
      before_install:
        # NASA CDF
        - wget -r -l1 -np -nd https://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ -A cdf*-dist-all.tar.gz
        - tar xf cdf*-dist-all.tar.gz
        - cd cdf*dist
        - make OS=linux ENV=gnu all
        - sudo make INSTALLDIR=/usr/local/cdf install
        - cd ..
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
      before_install:
        - pip3 install numpy==1.16.5
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      os: linux
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - os: windows

cache: pip

addons:
  apt:
    packages:
        gcc
        gfortran
        libc-dev
        python-dev
        libncurses5-dev


install:
  - python3 setup.py install || python setup.py install

script:
  - python3 magpy/test/test_di.py || python magpy/test/test_di.py
  - python3 magpy/test/test_read_write.py|| python magpy/test/test_read_write.py

